### ISSUE TITLE
v0.3.8 - App store approval

### ISSUE THREAD

**Issue by jlchereau** [Memba/Memba-Blog#127]
App store approval

- N/A

### Miscellaneous

- [x] #128 - Fix selenium tests following selenium-standalone v6.13.0
- [x] #129 - Review structured data (RDFa, microData and JSON-LD)
- [x] #130 - Fix jQuery is undefined on contact page
- [x] #132 - ReferenceError: Can't find variable: Promise (with Firefox 43) 

### Compare

https://github.com/Memba/Memba-Blog/compare/v0.3.7...v0.3.8
