### ISSUE TITLE
v0.3.9 - Redesign kendo.data.ScoreActivity and kendo.data.Stream (incl. mobile)

### ISSUE THREAD

**Issue by jlchereau** [Memba/Memba-Blog#133]
Redesign kendo.data.ScoreActivity and kendo.data.Stream (incl. mobile)

- N/A

### Miscellaneous

- [ ] #123 - Post contact us page to blog route and slack
- [ ] #124 - Add links to mobile apps
- [ ] #125 - Link to our gitter communities

### Compare

https://github.com/Memba/Memba-Blog/compare/v0.3.8...v0.3.9
